apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-mcp-server
  namespace: test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-mcp-server
  template:
    metadata:
      labels:
        app: db-mcp-server
    spec:
      serviceAccountName: mcp-server-sa # This is the name of the service account used in vault
      containers:
        - name: db-mcp-server
          image: 13rottenbanana/db-mcp-server:latest 
          ports:
            - containerPort: 3000
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_HOST
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PORT
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASS
          resources:
            requests:
              memory: "128Mi"
              cpu: "100m"
            limits:
              memory: "256Mi"
              cpu: "200m"