apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: test
  annotations:
    avp.kubernetes.io/path: "secrets/data/mcp-server/db" # This is used to tell AVP to use this secret for the MCP server
type: Opaque
stringData:
  DB_HOST: <DB_HOST>
  DB_PORT: <DB_PORT>
  DB_NAME: <DB_NAME>
  DB_USER: <DB_USER>
  DB_PASS: <DB_PASS>