apiVersion: v1
kind: ServiceAccount
metadata:
  name: mcp-server-sa # This is the name of the service account used in vault
  namespace: test # This is the namespace of the service account used in vault